// This file has been generated by comet admin-generator.
// You may choose to use this file as scaffold by moving this file out of generated folder and removing this comment.

import { gql } from "@apollo/client";

export const orderFormCustomerFragment = gql`
    fragment OrderFormCustomer on Customer {
        id
        firstname
        lastname
    }
`;

export const orderFormProductFragment = gql`
    fragment OrderFormProduct on Product {
        id
        name
    }
`;

export const orderFormFragment = gql`
    fragment OrderForm on Order {
        isPaid
        date
        customer {
            ...OrderFormCustomer
        }
        products {
            ...OrderFormProduct
        }
    }
    ${orderFormCustomerFragment}
    ${orderFormProductFragment}
`;

export const orderFormQuery = gql`
    query OrderForm($id: ID!) {
        order(id: $id) {
            id
            updatedAt
            ...OrderForm
        }
    }
    ${orderFormFragment}
`;

export const orderFormCheckForChangesQuery = gql`
    query OrderFormCheckForChanges($id: ID!) {
        order(id: $id) {
            updatedAt
        }
    }
`;

export const createOrderMutation = gql`
    mutation CreateOrder($input: OrderInput!) {
        createOrder(input: $input) {
            id
            updatedAt
            ...OrderForm
        }
    }
    ${orderFormFragment}
`;

export const updateOrderMutation = gql`
    mutation UpdateOrder($id: ID!, $input: OrderUpdateInput!, $lastUpdatedAt: DateTime) {
        updateOrder(id: $id, input: $input, lastUpdatedAt: $lastUpdatedAt) {
            id
            updatedAt
            ...OrderForm
        }
    }
    ${orderFormFragment}
`;

export const orderFormCustomersQuery = gql`
    query OrderFormCustomers {
        # don't hardcode limit in real app
        customers(limit: 50) {
            nodes {
                ...OrderFormCustomer
            }
        }
    }
    ${orderFormCustomerFragment}
`;

export const orderFormProductsQuery = gql`
    query OrderFormProducts {
        # don't hardcode limit in real app
        products(limit: 50) {
            nodes {
                ...OrderFormProduct
            }
        }
    }
    ${orderFormProductFragment}
`;
