// This file has been generated by comet admin-generator.
// You may choose to use this file as scaffold by moving this file out of generated folder and removing this comment.

import { useApolloClient, useQuery } from "@apollo/client";
import {
    Field,
    FinalForm,
    FinalFormAutocomplete,
    FinalFormCheckbox,
    FinalFormSaveSplitButton,
    FinalFormSubmitEvent,
    MainContent,
    Toolbar,
    ToolbarActions,
    ToolbarFillSpace,
    ToolbarItem,
    ToolbarTitleItem,
    useAsyncOptionsProps,
    useFormApiRef,
    useStackApi,
    useStackSwitchApi,
} from "@comet/admin";
import { FinalFormDatePicker } from "@comet/admin-date-time";
import { ArrowLeft } from "@comet/admin-icons";
import { EditPageLayout, queryUpdatedAt, resolveHasSaveConflict, useFormSaveConflict } from "@comet/cms-admin";
import { CircularProgress, FormControlLabel, IconButton } from "@mui/material";
import { FormApi } from "final-form";
import { filter } from "graphql-anywhere";
import React from "react";
import { FormattedMessage } from "react-intl";

import {
    createOrderMutation,
    orderFormCustomersQuery,
    orderFormFragment,
    orderFormProductsQuery,
    orderFormQuery,
    updateOrderMutation,
} from "./OrderForm.gql";
import {
    GQLCreateOrderMutation,
    GQLCreateOrderMutationVariables,
    GQLOrderFormCustomerFragment,
    GQLOrderFormCustomersQuery,
    GQLOrderFormCustomersQueryVariables,
    GQLOrderFormFragment,
    GQLOrderFormProductFragment,
    GQLOrderFormProductsQuery,
    GQLOrderFormProductsQueryVariables,
    GQLOrderFormQuery,
    GQLOrderFormQueryVariables,
    GQLUpdateOrderMutation,
    GQLUpdateOrderMutationVariables,
} from "./OrderForm.gql.generated";

type FormValues = Omit<GQLOrderFormFragment, "totalAmountPaid"> & {
    totalAmountPaid: string;
};

interface FormProps {
    id?: string;
}

export function OrderForm({ id }: FormProps): React.ReactElement {
    const stackApi = useStackApi();
    const client = useApolloClient();
    const mode = id ? "edit" : "add";
    const formApiRef = useFormApiRef<FormValues>();
    const stackSwitchApi = useStackSwitchApi();

    const { data, error, loading, refetch } = useQuery<GQLOrderFormQuery, GQLOrderFormQueryVariables>(
        orderFormQuery,
        id ? { variables: { id } } : { skip: true },
    );

    const initialValues = React.useMemo<Partial<FormValues>>(
        () =>
            data?.order
                ? {
                      ...filter<GQLOrderFormFragment>(orderFormFragment, data.order),
                      customer: data.order.customer,
                      products: data.order.products,
                  }
                : { products: [] },
        [data],
    );

    const saveConflict = useFormSaveConflict({
        checkConflict: async () => {
            const updatedAt = await queryUpdatedAt(client, "order", id);
            return resolveHasSaveConflict(data?.order.updatedAt, updatedAt);
        },
        formApiRef,
        loadLatestVersion: async () => {
            await refetch();
        },
    });

    const handleSubmit = async (state: FormValues, form: FormApi<FormValues>, event: FinalFormSubmitEvent) => {
        if (await saveConflict.checkForConflicts()) {
            throw new Error("Conflicts detected");
        }

        const output = {
            ...state,
            customer: state.customer.id,
            products: state.products.map((product) => product.id),
        };

        if (mode === "edit") {
            if (!id) {
                throw new Error("Missing id in edit mode");
            }
            await client.mutate<GQLUpdateOrderMutation, GQLUpdateOrderMutationVariables>({
                mutation: updateOrderMutation,
                variables: { id, input: output, lastUpdatedAt: data?.order?.updatedAt },
            });
        } else {
            const { data: mutationReponse } = await client.mutate<GQLCreateOrderMutation, GQLCreateOrderMutationVariables>({
                mutation: createOrderMutation,
                variables: { input: output },
            });
            if (!event.navigatingBack) {
                const id = mutationReponse?.createOrder.id;
                if (id) {
                    setTimeout(() => {
                        stackSwitchApi.activatePage("edit", id);
                    });
                }
            }
        }
    };

    const selectCustomerAsyncProps = useAsyncOptionsProps<GQLOrderFormCustomerFragment>(async () => {
        const { data, error } = await client.query<GQLOrderFormCustomersQuery, GQLOrderFormCustomersQueryVariables>({
            query: orderFormCustomersQuery,
        });

        if (error) {
            throw new Error("Can't load customers");
        }

        return data.customers.nodes;
    });

    const selectProductsAsyncProps = useAsyncOptionsProps<GQLOrderFormProductFragment>(async () => {
        const { data, error } = await client.query<GQLOrderFormProductsQuery, GQLOrderFormProductsQueryVariables>({
            query: orderFormProductsQuery,
        });

        if (error) {
            throw new Error("Can't load products");
        }

        return data.products.nodes;
    });

    if (error) throw error;

    if (loading) {
        return <CircularProgress />;
    }

    return (
        <FinalForm<FormValues>
            apiRef={formApiRef}
            onSubmit={handleSubmit}
            mode={mode}
            initialValues={initialValues}
            onAfterSubmit={(values, form) => {
                //don't go back automatically
            }}
        >
            {({ values }) => (
                <EditPageLayout>
                    {saveConflict.dialogs}
                    <Toolbar>
                        <ToolbarItem>
                            <IconButton onClick={stackApi?.goBack}>
                                <ArrowLeft />
                            </IconButton>
                        </ToolbarItem>
                        <ToolbarTitleItem>
                            {mode == "edit" ? (
                                <FormattedMessage id="orders.editOrder" defaultMessage="Edit Order" />
                            ) : (
                                <FormattedMessage id="orders.newOrder" defaultMessage="New Order" />
                            )}
                        </ToolbarTitleItem>
                        <ToolbarFillSpace />
                        <ToolbarActions>
                            <FinalFormSaveSplitButton />
                        </ToolbarActions>
                    </Toolbar>
                    <MainContent>
                        <Field name="isPaid" label="" type="checkbox" fullWidth>
                            {(props) => (
                                <FormControlLabel
                                    label={<FormattedMessage id="order.isPaid" defaultMessage="Is Paid" />}
                                    control={<FinalFormCheckbox {...props} />}
                                />
                            )}
                        </Field>
                        <Field
                            required
                            fullWidth
                            name="date"
                            component={FinalFormDatePicker}
                            label={<FormattedMessage id="order.date" defaultMessage="Date" />}
                        />
                        <Field
                            label={<FormattedMessage id="order.customer" defaultMessage="Customer" />}
                            name="customer"
                            component={FinalFormAutocomplete}
                            {...selectCustomerAsyncProps}
                            getOptionLabel={(option: GQLOrderFormCustomerFragment) => `${option.firstname} ${option.lastname}`}
                            getOptionSelected={(option: GQLOrderFormCustomerFragment, value: GQLOrderFormCustomerFragment) => {
                                return option.id === value.id;
                            }}
                            fullWidth
                        />
                        <Field
                            label={<FormattedMessage id="order.shopProducts" defaultMessage="Products" />}
                            name="products"
                            component={FinalFormAutocomplete}
                            multiple
                            {...selectProductsAsyncProps}
                            getOptionLabel={(option: GQLOrderFormProductFragment) => option.name}
                            isOptionEqualToValue={(option: GQLOrderFormProductFragment, value: GQLOrderFormProductFragment) => option.id === value.id}
                            fullWidth
                        />
                    </MainContent>
                </EditPageLayout>
            )}
        </FinalForm>
    );
}
