// This file has been generated by comet api-generator.
// You may choose to use this file as scaffold by moving this file out of generated folder and removing this comment.
import { OffsetBasedPaginationArgs } from "@comet/cms-api";
import { ArgsType, Field } from "@nestjs/graphql";
import { Type } from "class-transformer";
import { IsOptional, IsString, ValidateNested } from "class-validator";

import { OrderFilter } from "./order.filter";
import { OrderSort } from "./order.sort";

@ArgsType()
export class OrdersArgs extends OffsetBasedPaginationArgs {
    @Field({ nullable: true })
    @IsOptional()
    @IsString()
    search?: string;

    @Field(() => OrderFilter, { nullable: true })
    @ValidateNested()
    @Type(() => OrderFilter)
    @IsOptional()
    filter?: OrderFilter;

    @Field(() => [OrderSort], { nullable: true })
    @ValidateNested({ each: true })
    @Type(() => OrderSort)
    @IsOptional()
    sort?: OrderSort[];
}
